### ISSUE TITLE
Cell_type option

### ISSUE THREAD

**Issue by 2miatran** [ZhiGroup/pytorch_ehr#16]
Currently user can input any cell_type (e.g. celltype of "QRNN" for EHR_RNN model), leading to some mismatch in handling packPadMode.  
=> Restrict cell_type option to "RNN", "GRU", "LSTM". 
=> Make cell_type of "QRNN" and "TLSTM" a default for qrnn, tlstm model.

**Comment by lrasmy** [comment]
Solved  ## LR 11/6/19
