### ISSUE TITLE
i followed the exact step in using the code but i keep getting this error

### ISSUE THREAD

**Issue by Seyi017** [ZhiGroup/pytorch_ehr#19]
![16483161064763488771889378817819](https://user-images.githubusercontent.com/102433846/160254907-89ff8ac4-af29-457a-a2dc-8dc92fbdb460.jpg)

**Comment by lrasmy** [comment]
Hi Seyi017,

This error is mostly indicating that something is not matching in the preprocessed data.

Most commonly, you have a token_id larger than the input_size used to create the embedding layer. 
and sometimes the format or the structure of the pickled lists are not exactly as expected by the model.

if you are following the ACM-BCB-Tutorial branch, please make sure that you are using the exact pre-processing code in that branch and not the code on the master, and vice versa.

Please let us know if this solves your issue

Thanks,
Laila

**Comment by Seyi017** [comment]
I checked the other tutorial but I couldn't find the branch only the master is available

**Comment by lrasmy** [comment]
Hi @Seyi017 , this is the direct link for the tutorial branch https://github.com/ZhiGroup/pytorch_ehr/tree/ACM_BCB-Tutorial

Thanks
