### ISSUE TITLE
lr_DHF_tmp5_demo_socioe.txt file for Diabetes ML

### ISSUE THREAD

**Issue by scherbakovdmitri** [ZhiGroup/pytorch_ehr#21]
Good day! Where can I get this file for Diabetes notebook? thanks!

**Comment by lrasmy** [comment]
Hi @scherbakovdmitri ,

For the tutorial files in the master branch, we are not sharing any data files.

Alternatively, I'd recommend you use any of the tutorial branches, for example https://github.com/ZhiGroup/pytorch_ehr/tree/ACM_BCB-Tutorial
is using synthetic data that you can easily use while testing the repo on google collab as per the instructions in the branch's read me

Thanks,
Laila
